#!/bin/sh
#
# Copyright (C) 2016 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: build-ami
# Purpose:
#   Build VyOS AMI.

if [ ! $(which vmdk-convert) ]; then
   echo "Your system doesn't have vmdk-convert. Please install it from https://github.com/vmware/open-vmdk."
   exit 1
else
   echo "Your system has vmdk-convert."
fi

if [ ! $(which ovftool) ]; then
   echo "Your system doesn't have ovftool. Please install it from https://www.vmware.com/support/developer/ovf/."
   exit 1
else
   echo "Your system has ovftool."
fi

export PACKER_BUILD_DIR=packer_build
export PACKER_LOG_PATH=${PACKER_BUILD_DIR}/build_ami.log
export PACKER_LOG=1

mkdir -p ${PACKER_BUILD_DIR}
DST_DIR=${PACKER_BUILD_DIR}/ami

packer build -only=ami scripts/packer.json

# Convert raw image to VMDK
source_image=${DST_DIR}/vyos_ami_image.img
tmp_vmdk=${DST_DIR}/tmp.vmdk
vmdk=${DST_DIR}/vyos_ami_image.vmdk
ovf=${DST_DIR}/vyos_ami_image.ovf
qemu-img convert -f raw ${source_image} -O vmdk -o adapter_type=lsilogic ${tmp_vmdk}
vmdk-convert ${tmp_vmdk} ${vmdk}

# Generate OVF
echo 'Generating OVF file...'
vmdk_file_name=$(basename ${vmdk})
vmdk_file_size=$(du --bytes ${vmdk} | cut -f1)
vmdk_populated_size=$(vmdk-convert -i ${vmdk} | jq .used)
version=$(cat build/version)
sed scripts/template.ovf \
  -e "s/{{vmdk_file_name}}/${vmdk_file_name}/" \
  -e "s/{{vmdk_file_size}}/${vmdk_file_size}/" \
  -e "s/{{vmdk_populated_size}}/${vmdk_populated_size}/" \
  -e "s/{{version}}/${version}/" \
  > ${ovf}

# Generate manifest file
cd ${DST_DIR}
openssl sha1 *.vmdk *.ovf > vyos_ami_image.mf

# Convert the OVF to OVA...
echo 'Converting the OVF to OVA...'
ovftool vyos_ami_image.ovf vyos_ami_image.ova
