#!/bin/sh
#
# Copyright (C) 2016 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: build-vmware-image
# Purpose:
#   Build VyOS OVA and OVF for VMware.

export PACKER_BUILD_DIR=packer_build

DST_DIR=${PACKER_BUILD_DIR}/azure

packer build -only=azure-image scripts/packer.json

# Convert raw image to VHD
source_image=${PACKER_BUILD_DIR}/azure/vyos_azure_image.img
vhd=${DST_DIR}/vyos_azure_image.vhd
qemu-img convert -f raw ${source_image} -O vpc ${vhd} -o subformat=fixed
